#!/bin/sh
ssh -tt -o StrictHostKeyChecking=nolakshay@165.22.112.115<<EOF
  cd jenkins-testing
  git pull origin master
  npm install --production
  npm install -g pm2
  pm2 stop all
  pm2 start app.js
  exit
EOF